//Config file for the program
//Syntax: {falg, value}
//Flags: checkTime, allowedRoomAmount, returnToHomeTimeout, saveTemporaryUsers

const config = [
    {checkTime: [22,45]},
    {allowedRoomAmount: 2},
    {returnToHomeTimeout: 1},
]

//Syntax: [room, flag, value]
//Falgs: roomSpace, roomGender

const roomConfig = [

]

// Base configuration
// Syntax: [roomNumber, capacity, houseGroup]
// Room gender is autogenerated, but can also be manually set with roomConfig
/*
 * roomNumber: The room number of the room.
 * capacity: The amount of people allowed to sleep in the room.
 * houseGroup: If part of the rooms are in seperate buildings 
*/
const roomLayout = [
    
]