//Config file for the program
//Syntax: {falg, value}
//Flags: checkTime<[Hour,Minute]>, allowedRoomAmount<Count>, returnToHomeTimeout<Minute>, saveTemporaryUsers<Bool>, temporaryUserTimeout<Hour>

const config = [
    {checkTime: [22,45]},
    {allowedRoomAmount: 2},
    {returnToHomeTimeout: 1},
    {saveTemporaryUsers: true},
    {temporaryUserTimeout: 48},
]

//Syntax: [room, flag, value]
//Falgs: roomSpace, roomGender

const roomConfig = [

]

/*
The house layout configures the different houses. Here you can set things as: amount of rooms, house names and house number.
Room gender is autogenerated, but can also be manually set with roomConfig.
There can be a max of 6 houses.

 * capacity: The amount of room located in that spicifc house. (20 is max)
 * houseName: The name of the spicific house.
 * houseNumber: Used to configere what order the houses are displayed, and assign rooms to a spicifc house.

 * {capacity:0, houseName:"Name", houseNumber:0}
*/

const houseLayout = [
    {capacity:13, houseName:"Asgård", houseNumber:3},
    {capacity:13, houseName:"Midgård", houseNumber:4},
    {capacity:13, houseName:"Udgård", houseNumber:2},
    {capacity:6, houseName:"Valhal", houseNumber:1}
]

/*
The room layout configures either one or multiple rooms inside a spicific house.

 * roomNumber: The room number of the room.
 * capacity: The amount of people allowed to sleep in the room.
 * houseGroup: If part of the rooms are in seperate buildings 

 * {capacity:0, roomNumber:0, houseGroup:0}

If multiple rooms share the same values you can use this format instead:
Although this only works if the rooms follow numerical order: 1-2-3-4-5... customs like 1a-1b-1c... don't work.
Both numbers ARE included so 3-12 would be: 3-4-5-6...10-11-12
 * {capacity:0, roomNumber:"0-10", houseGroup:0}
*/
const roomLayout = [
    {capacity:2, roomNumber:"1a", houseGroup:4},
    {capacity:3, roomNumber:"1b", houseGroup:4},
    {capacity:4, roomNumber:2, houseGroup:4},
    {capacity:3, roomNumber:"3-12", houseGroup:4},
    
    {capacity:3, roomNumber:14, houseGroup:3},
    {capacity:4, roomNumber:15, houseGroup:3},
    {capacity:3, roomNumber:"16-26", houseGroup:3},
    
    {capacity:3, roomNumber:27, houseGroup:2},
    {capacity:4, roomNumber:28, houseGroup:2},
    {capacity:3, roomNumber:"29-39", houseGroup:2},
    
    {capacity:3, roomNumber:"40-45", houseGroup:1}
]