// Data Converter: https://shancarter.github.io/mr-data-converter/
//To change the data follow these steps:
//--link

const data = [{"number":133,"name":"Adelina Høst Johnsen","img":"viggo-billeder/A/Adelina.jpg","room":44,"choice":"NAN","sex":"f"},
{"number":7,"name":"Albert Damsgaard Grønnerup","img":"viggo-billeder/A/Albert.jpg","room":19,"choice":"NAN","sex":"m"},
{"number":81,"name":"Alberte Holmgaard Grønfeldt","img":"viggo-billeder/A/Alberte.jpg","room":38,"choice":"NAN","sex":"f"},
{"number":14,"name":"Alexander Damgård","img":"viggo-billeder/A/Alexander.jpg","room":42,"choice":"NAN","sex":"m"},
{"number":82,"name":"Alma Frøhlich Hougaard","img":"viggo-billeder/A/Alma.jpg","room":45,"choice":"NAN","sex":"f"},
{"number":73,"name":"Amalie Korfitz Nielsen","img":"viggo-billeder/A/Amalie.jpg","room":34,"choice":"NAN","sex":"f"},
{"number":97,"name":"Andrea Bjørnskov Bergholt","img":"viggo-billeder/A/Andrea1.jpg","room":15,"choice":"NAN","sex":"f"},
{"number":103,"name":"Andrea Nørup Andersen","img":"viggo-billeder/A/Andrea2.jpg","room":17,"choice":"NAN","sex":"f"},
{"number":139,"name":"Angelina Christensen Lyberth","img":"viggo-billeder/A/Angelina.jpg","room":38,"choice":"NAN","sex":"f"},
{"number":41,"name":"Anne Wilstrup Holst","img":"viggo-billeder/A/Anne.jpg","room":2,"choice":"NAN","sex":"f"},
{"number":134,"name":"Anton Hermansen","img":"viggo-billeder/A/Anton1.jpg","room":23,"choice":"NAN","sex":"m"},
{"number":44,"name":"Anton Bissø Stausholm","img":"viggo-billeder/A/Anton2.jpg","room":12,"choice":"NAN","sex":"m"},
{"number":65,"name":"Anton Haukrog Møller","img":"viggo-billeder/A/Anton3.jpg","room":14,"choice":"NAN","sex":"m"},
{"number":6,"name":"Astrid Marie Kirkegaard","img":"viggo-billeder/A/Astrid.jpg","room":40,"choice":"NAN","sex":"f"},
{"number":131,"name":"Baylee Halfdan Søgård Fink","img":"viggo-billeder/B/Baylee.jpg","room":27,"choice":"NAN","sex":"m"},
{"number":27,"name":"Benjamin Samuel Nielsen Nicolajsen","img":"viggo-billeder/B/Benjamin.jpg","room":10,"choice":"NAN","sex":"m"},
{"number":98,"name":"Camilla Lehmann Jessen","img":"viggo-billeder/C/Camilla.jpg","room":11,"choice":"NAN","sex":"f"},
{"number":127,"name":"Camille Staberg Simonsen","img":"viggo-billeder/C/Camille.jpg","room":40,"choice":"NAN","sex":"f"},
{"number":52,"name":"Carolina Aagaard","img":"viggo-billeder/C/Carolina.jpg","room":34,"choice":"NAN","sex":"f"},
{"number":47,"name":"Caroline Flintholm Juelsgaard","img":"viggo-billeder/C/Caroline1.jpg","room":15,"choice":"NAN","sex":"f"},
{"number":45,"name":"Caroline Sax Riggelsen","img":"viggo-billeder/C/Caroline2.jpg","room":39,"choice":"NAN","sex":"f"},
{"number":60,"name":"Cecilie Damsgaard Paulsen","img":"viggo-billeder/C/Cecilie1.jpg","room":22,"choice":"NAN","sex":"f"},
{"number":108,"name":"Cecilie Margrethe Christiansen","img":"viggo-billeder/C/Cecilie2.jpg","room":43,"choice":"NAN","sex":"f"},
{"number":77,"name":"Dicte Johanne Schultz","img":"viggo-billeder/D/Dicte.jpg","room":22,"choice":"NAN","sex":"f"},
{"number":136,"name":"Ella Zwergius Moreno","img":"viggo-billeder/E/Ella.jpg","room":11,"choice":"NAN","sex":"f"},
{"number":3,"name":"Emil Støttrup","img":"viggo-billeder/E/Emil.jpg","room":27,"choice":"NAN","sex":"m"},
{"number":116,"name":"Emma Lindberg Jensen","img":"viggo-billeder/E/Emma.jpg","room":30,"choice":"NAN","sex":"f"},
{"number":75,"name":"Esben Petersen","img":"viggo-billeder/E/Esben.jpg","room":"1b","choice":"NAN","sex":"m"},
{"number":21,"name":"Eva Raahauge Muntenjon","img":"viggo-billeder/E/Eva.jpg","room":9,"choice":"NAN","sex":"f"},
{"number":96,"name":"Evelina Spelmane","img":"viggo-billeder/E/Evelina.jpg","room":30,"choice":"NAN","sex":"f"},
{"number":78,"name":"Faye Randris Rowlands","img":"viggo-billeder/F/Faye.jpg","room":45,"choice":"NAN","sex":"f"},
{"number":8,"name":"Frederik Haugaard Brunsgaard","img":"viggo-billeder/F/Frederik1.jpg","room":23 ,"choice":"NAN","sex":"m"},
{"number":18,"name":"Frederik Højmark Pedersen","img":"viggo-billeder/F/Frederik2.jpg","room":24,"choice":"NAN","sex":"m"},
{"number":111,"name":"Frederik William Dirksen","img":"viggo-billeder/F/Frederik3.jpg","room":10,"choice":"NAN","sex":"m"},
{"number":110,"name":"Freja Michelle Andersen","img":"viggo-billeder/F/Freja.jpg","room":37,"choice":"NAN","sex":"f"},
{"number":61,"name":"Frida Friis Thomsen","img":"viggo-billeder/F/Frida1.jpg","room":26,"choice":"NAN","sex":"f"},
{"number":138,"name":"Frida Peters Lassen","img":"viggo-billeder/F/Frida2.jpg","room":2,"choice":"NAN","sex":"f"},
{"number":64,"name":"Frida Søgaard Thomsen","img":"viggo-billeder/F/Frida3.jpg","room":39,"choice":"NAN","sex":"f"},
{"number":63,"name":"Gry Lindholm Tollgaard","img":"viggo-billeder/G/Gry.jpg","room":44,"choice":"NAN","sex":"f"},
{"number":20,"name":"Gunna Rump Vejlø","img":"viggo-billeder/G/Gunna.jpg","room":33,"choice":"NAN","sex":"f"},
{"number":99,"name":"Halfdan Jacobsen Kirkegaard","img":"viggo-billeder/H/Halfdan.jpg","room":29,"choice":"NAN","sex":"m"},
{"number":36,"name":"Hannibal Ingeberg","img":"viggo-billeder/H/Hannibal.jpg","room":41,"choice":"NAN","sex":"m"},
{"number":67,"name":"Harald Brøcker","img":"viggo-billeder/H/Harald.jpg","room":5,"choice":"NAN","sex":"m"},
{"number":56,"name":"Hjalte Wittek Sørensen","img":"viggo-billeder/H/Hjalte.jpg","room":"1b","choice":"NAN","sex":"m"},
{"number":34,"name":"Hugo Qvist Tøpholm","img":"viggo-billeder/H/Hugo.jpg","room":41,"choice":"NAN","sex":"m"},
{"number":92,"name":"Ingeborg Bruun Hinrichsen","img":"viggo-billeder/I/Ingeborg.jpg","room":21,"choice":"NAN","sex":"f"},
{"number":112,"name":"Isabella Kirstine Neuberg Rasmussen","img":"viggo-billeder/I/Isabella.jpg","room":39,"choice":"NAN","sex":"f"},
{"number":76,"name":"Jens Møller Martin","img":"viggo-billeder/J/Jens.jpg","room":31,"choice":"NAN","sex":"m"},
{"number":120,"name":"Jeppe Holm Jensen","img":"viggo-billeder/J/Jeppe.jpg","room":29,"choice":"NAN","sex":"m"},
{"number":32,"name":"Johan Lading Katballe","img":"viggo-billeder/J/Johan1.jpg","room":19 ,"choice":"NAN","sex":"m"},
{"number":43,"name":"Johan Stenkil Lajer","img":"viggo-billeder/J/Johan2.jpg","room":5,"choice":"NAN","sex":"m"},
{"number":16,"name":"Jonas Rotne","img":"viggo-billeder/J/Jonas1.jpg","room":20,"choice":"NAN","sex":"m"},
{"number":128,"name":"Jonas Staghøj Markussen","img":"viggo-billeder/J/Jonas2.jpg","room":31,"choice":"NAN","sex":"m"},
{"number":88,"name":"Julie Christensen Venø","img":"viggo-billeder/J/Julie1.jpg","room":25,"choice":"NAN","sex":"f"},
{"number":54,"name":"Julie Lykke Lolck","img":"viggo-billeder/J/Julie2.jpg","room":22,"choice":"NAN","sex":"f"},
{"number":1,"name":"Karla Kobberø","img":"viggo-billeder/K/Karla1.jpg","room":43,"choice":"NAN","sex":"f"},
{"number":53,"name":"Karla Weimar Schousen","img":"viggo-billeder/K/Karla2.jpg","room":43,"choice":"NAN","sex":"f"},
{"number":69,"name":"Karoline Pagaard Christensen","img":"viggo-billeder/K/Karoline.jpg","room":11,"choice":"NAN","sex":"f"},
{"number":93,"name":"Katja Nygaard-Larsen","img":"viggo-billeder/K/Katja.jpg","room":26,"choice":"NAN","sex":"f"},
{"number":94,"name":"Katrine Brylle","img":"viggo-billeder/K/Katrine.jpg","room":37,"choice":"NAN","sex":"f"},
{"number":124,"name":"Kirstine Ammiztbøll Christensen","img":"viggo-billeder/K/Kirstine.jpg","room":4,"choice":"NAN","sex":"f"},
{"number":91,"name":"Kristoffer Rehhoff-Nør","img":"viggo-billeder/K/Kristoffer.jpg","room":36,"choice":"NAN","sex":"m"},
{"number":68,"name":"Laura Vinther Jepsen","img":"viggo-billeder/L/Laura.jpg","room":26,"choice":"NAN","sex":"f"},
{"number":72,"name":"Lina Høft Homilius","img":"viggo-billeder/L/Lina.jpg","room":45,"choice":"NAN","sex":"f"},
{"number":105,"name":"Liva Marie Mikel Schjelde","img":"viggo-billeder/L/Liva.jpg","room":17,"choice":"NAN","sex":"f"},
{"number":38,"name":"Lucas Steele Sørensen","img":"viggo-billeder/L/Lucas1.jpg","room":24,"choice":"NAN","sex":"m"},
{"number":37,"name":"Lucas Wittrup Jensen","img":"viggo-billeder/L/Lucas2.jpg","room":14,"choice":"NAN","sex":"m"},
{"number":101,"name":"Lykke Pagaard","img":"viggo-billeder/L/Lykke.jpg","room":15,"choice":"NAN","sex":"f"},
{"number":58,"name":"Magnus Beyer Bach Mortensen","img":"viggo-billeder/M/Magnus.jpg","room":32,"choice":"NAN","sex":"m"},
{"number":84,"name":"Malte Mervild Greve","img":"viggo-billeder/M/Malte.jpg","room":20,"choice":"NAN","sex":"m"},
{"number":135,"name":"Malthe Gustavussen","img":"viggo-billeder/M/Malthe1.jpg","room":18,"choice":"NAN","sex":"m"},
{"number":79,"name":"Malthe Drud Vester Palle","img":"viggo-billeder/M/Malthe2.jpg","room":3,"choice":"NAN","sex":"m"},
{"number":22,"name":"Marcus Thorup","img":"viggo-billeder/M/Marcus.jpg","room":18,"choice":"NAN","sex":"m"},
{"number":46,"name":"Maria Løvlund Mandsberg","img":"viggo-billeder/M/Maria1.jpg","room":21,"choice":"NAN","sex":"f"},
{"number":83,"name":"Maria West Jørgensen","img":"viggo-billeder/M/Maria2.jpg","room":25,"choice":"NAN","sex":"f"},
{"number":117,"name":"Marie Hebsgaard Offersen","img":"viggo-billeder/M/Marie.jpg","room":40,"choice":"NAN","sex":"f"},
{"number":106,"name":"Marius Ehlert Degn Larsen","img":"viggo-billeder/M/Marius1.jpg","room":42,"choice":"NAN","sex":"m"},
{"number":87,"name":"Marius Kjeld Finnerup","img":"viggo-billeder/M/Marius2.jpg","room":20,"choice":"NAN","sex":"m"},
{"number":107,"name":"Marius Lykke Hansen","img":"viggo-billeder/M/Marius3.jpg","room":"1a","choice":"NAN","sex":"m"},
{"number":40,"name":"Mary Fischer Sloth","img":"viggo-billeder/M/Mary.jpg","room":4,"choice":"NAN","sex":"f"},
{"number":66,"name":"Mathias Bach Sølvbjerg Dolleris","img":"viggo-billeder/M/Mathias.jpg","room":24,"choice":"NAN","sex":"m"},
{"number":85,"name":"Mathilde Dræborg Evind","img":"viggo-billeder/M/Mathilde.jpg","room":33,"choice":"NAN","sex":"m"},
{"number":130,"name":"Merle Toft","img":"viggo-billeder/M/Merle.jpg","room":15,"choice":"NAN","sex":"f"},
{"number":10,"name":"Mette Kulby Rick","img":"viggo-billeder/M/Mette.jpg","room":33,"choice":"NAN","sex":"f"},
{"number":71,"name":"Mille Sandholdt","img":"viggo-billeder/M/Mille1.jpg","room":9,"choice":"NAN","sex":"f"},
{"number":25,"name":"Mille Schultz Bach","img":"viggo-billeder/M/Mille2.jpg","room":8,"choice":"NAN","sex":"f"},
{"number":129,"name":"Mille Sophia Damsø","img":"viggo-billeder/M/Mille3.jpg","room":17,"choice":"NAN","sex":"f"},
{"number":86,"name":"Mina Skjoldby Foss","img":"viggo-billeder/M/Mina.jpg","room":8,"choice":"NAN","sex":"f"},
{"number":132,"name":"Nagi Nishioka","img":"viggo-billeder/N/Nagi.jpg","room":27,"choice":"NAN","sex":"m"},
{"number":114,"name":"Nanna Lerche Freudendal","img":"viggo-billeder/N/Nanna.jpg","room":34,"choice":"NAN","sex":"f"},
{"number":123,"name":"Nellie Berg Pedersen","img":"viggo-billeder/N/Nellie.jpg","room":21,"choice":"NAN","sex":"f"},
{"number":42,"name":"Noah Bue Pilgaard","img":"viggo-billeder/N/Noah1.jpg","room":16,"choice":"NAN","sex":"m"},
{"number":12,"name":"Noah Grøndahl Lassen","img":"viggo-billeder/N/Noah2.jpg","room":6,"choice":"NAN","sex":"m"},
{"number":24,"name":"Noah Aarhus Petersen","img":"viggo-billeder/N/Noah3.jpg","room":36,"choice":"NAN","sex":"m"},
{"number":102,"name":"Ole Carl Risak Schou","img":"viggo-billeder/O/Ole.jpg","room":3,"choice":"NAN","sex":"m"},
{"number":9,"name":"Oliver Gaba Lylover","img":"viggo-billeder/O/Oliver1.jpg","room":36,"choice":"NAN","sex":"m"},
{"number":51,"name":"Oliver Scott Walters","img":"viggo-billeder/O/Oliver2.jpg","room":31,"choice":"NAN","sex":"m"},
{"number":62,"name":"Peter Bille Røhling","img":"viggo-billeder/P/Peter.jpg","room":32,"choice":"NAN","sex":"m"},
{"number":35,"name":"Philip Hilstrøm Sørensen","img":"viggo-billeder/P/Philip.jpg","room":16,"choice":"NAN","sex":"m"},
{"number":80,"name":"Rasmus Benjamin Jørgensen","img":"viggo-billeder/R/Rasmus1.jpg","room":32,"choice":"NAN","sex":"m"},
{"number":31,"name":"Rasmus Kirkeskov Hansen","img":"viggo-billeder/R/Rasmus2.jpg","room":6,"choice":"NAN","sex":"m"},
{"number":11,"name":"Rasmus Kyhn Boisen","img":"viggo-billeder/R/Rasmus3.jpg","room":12,"choice":"NAN","sex":"m"},
{"number":89,"name":"Rune Horsbøll Møller","img":"viggo-billeder/R/Rune.jpg","room":23,"choice":"NAN","sex":"m"},
{"number":90,"name":"Sara Møller Risdahl Knudsen","img":"viggo-billeder/S/Sara.jpg","room":2,"choice":"NAN","sex":"f"},
{"number":4,"name":"Sebastian Bisgaard","img":"viggo-billeder/S/Sebastian1.jpg","room":3,"choice":"NAN","sex":"m"},
{"number":122,"name":"Sebastian Skiby Esbjerg","img":"viggo-billeder/S/Sebastian2.jpg","room":5,"choice":"NAN","sex":"m"},
{"number":115,"name":"Sebastian Valdemar Sax Sielemann","img":"viggo-billeder/S/Sebastian3.jpg","room":"1a","choice":"NAN","sex":"m"},
{"number":50,"name":"Silje Andrea Palmelund Lindemann","img":"viggo-billeder/S/Silje.jpg","room":30,"choice":"NAN","sex":"f"},
{"number":30,"name":"Simon Wonsild Krogsgaard Andersen","img":"viggo-billeder/S/Simon.jpg","room":18,"choice":"NAN","sex":"m"},
{"number":95,"name":"Sofie Fynbo Christoffersen","img":"viggo-billeder/S/Sofie.jpg","room":9,"choice":"NAN","sex":"f"},
{"number":5,"name":"Svend Nielsen Korsholm","img":"viggo-billeder/S/Svend.jpg","room":42,"choice":"NAN","sex":"m"},
{"number":109,"name":"Tea Bendixen","img":"viggo-billeder/T/Tea.jpg","room":37,"choice":"NAN","sex":"f"},
{"number":17,"name":"Thea Dalsgaard Kallesø","img":"viggo-billeder/T/Thea.jpg","room":17,"choice":"NAN","sex":"f"},
{"number":29,"name":"Tobias Grønskov Hansen","img":"viggo-billeder/T/Tobias1.jpg","room":35,"choice":"NAN","sex":"m"},
{"number":28,"name":"Tobias Høgh Veis","img":"viggo-billeder/T/Tobias2.jpg","room":41,"choice":"NAN","sex":"m"},
{"number":55,"name":"Torbjørn Hornemann Nielsen","img":"viggo-billeder/T/Torbjørn.jpg","room":6,"choice":"NAN","sex":"m"},
{"number":19,"name":"Tristian Alexander Hald","img":"viggo-billeder/T/Tristian.jpg","room":35,"choice":"NAN","sex":"m"},
{"number":33,"name":"Troels Kragerup Lundin","img":"viggo-billeder/T/Troels.jpg","room":29,"choice":"NAN","sex":"m"},
{"number":59,"name":"Tue Storm Mathiasen","img":"viggo-billeder/T/Tue.jpg","room":10,"choice":"NAN","sex":"m"},
{"number":2,"name":"Victor Albert Christensen","img":"viggo-billeder/V/Victor.jpg","room":35,"choice":"NAN","sex":"m"},
{"number":121,"name":"Victoria Roskvist","img":"viggo-billeder/V/Victoria.jpg","room":8,"choice":"NAN","sex":"f"},
{"number":48,"name":"Vigga Burmeister Clausen","img":"viggo-billeder/V/Vigga.jpg","room":4,"choice":"NAN","sex":"f"},
{"number":39,"name":"Vilma Tolstrup Melgaard","img":"viggo-billeder/V/Vilma.jpg","room":2,"choice":"NAN","sex":"f"},
{"number":13,"name":"Zenia Karen Van Der Plas","img":"viggo-billeder/Z/Zenia.jpg","room":38,"choice":"NAN","sex":"f"}]